CREATE TABLE IF NOT EXISTS notes (
    noteID INTEGER PRIMARY KEY AUTOINCREMENT,
    noteName TEXT NOT NULL,
    category TEXT NOT NULL,
    noteCreate DATETIME DEFAULT CURRENT_TIMESTAMP,
    filePath TEXT NOT NULL
);
